const skillToCategory = {
  "ABAP": "Programming Languages",
  "APL": "Programming Languages",
  "ActionScript": "Programming Languages",
  "Ada": "Programming Languages",
  "Apex": "Programming Languages",
  "Assembly": "Programming Languages",
  "Ballerina": "Programming Languages",
  "Bash": "Programming Languages",
  "C": "Programming Languages",
  "C#": "Programming Languages",
  "C++": "Programming Languages",
  "COBOL": "Programming Languages",
  "Carbon": "Programming Languages",
  "Ceylon": "Programming Languages",
  "Clojure": "Programming Languages",
  "Crystal": "Programming Languages",
  "D": "Programming Languages",
  "Dart": "Programming Languages",
  "Delphi": "Programming Languages",
  "Eiffel": "Programming Languages",
  "Elixir": "Programming Languages",
  "Elm": "Programming Languages",
  "Erlang": "Programming Languages",
  "F#": "Programming Languages",
  "Forth": "Programming Languages",
  "Fortran": "Programming Languages",
  "Go": "Programming Languages",
  "GraphQL": "Programming Languages",
  "Groovy": "Programming Languages",
  "Hack": "Programming Languages",
  "Haskell": "Programming Languages",
  "J": "Programming Languages",
  "Java": "Programming Languages",
  "JavaScript": "Programming Languages",
  "Julia": "Programming Languages",
  "Kotlin": "Programming Languages",
  "Lisp": "Programming Languages",
  "Lua": "Programming Languages",
  "MATLAB": "Programming Languages",
  "Nim": "Programming Languages",
  "OCaml": "Programming Languages",
  "Objective-C": "Programming Languages",
  "Octave": "Programming Languages",
  "PHP": "Programming Languages",
  "PL/SQL": "Programming Languages",
  "Pascal": "Programming Languages",
  "Perl": "Programming Languages",
  "Pony": "Programming Languages",
  "PowerShell": "System Administration",
  "Prolog": "Programming Languages",
  "PureScript": "Programming Languages",
  "Python": "Programming Languages",
  "Q#": "Programming Languages",
  "R": "Programming Languages",
  "RPG": "Programming Languages",
  "Racket": "Programming Languages",
  "ReScript": "Programming Languages",
  "Reason": "Programming Languages",
  "Ruby": "Programming Languages",
  "Rust": "Programming Languages",
  "SAS": "Programming Languages",
  "SQL": "Databases",
  "Scala": "Programming Languages",
  "Scheme": "Programming Languages",
  "Smalltalk": "Programming Languages",
  "Solidity": "Blockchain",
  "Standard ML": "Programming Languages",
  "Swift": "Programming Languages",
  "T-SQL": "Programming Languages",
  "Tcl": "Programming Languages",
  "TypeScript": "Programming Languages",
  "V": "Programming Languages",
  "VBA": "Programming Languages",
  "VHDL": "Programming Languages",
  "Verilog": "Programming Languages",
  "Visual Basic": "Programming Languages",
  "Zig": "Programming Languages",
  "ActiveRecord": "Database ORMs",
  "Alembic": "Database ORMs",
  "Dapper": "Database ORMs",
  "Diesel": "Database ORMs",
  "Doctrine ORM": "Database ORMs",
  "Entity Framework": "Database ORMs",
  "GORM": "Databases",
  "Hibernate": "Databases",
  "JPA": "Database ORMs",
  "Knex.js": "Database ORMs",
  "NHibernate": "Database ORMs",
  "SQLAlchemy": "Database ORMs",
  "Sequelize": "Databases",
  "TypeORM": "Databases",
  "sqlx": "Database ORMs",
  "Akka.NET": "rpc_and_microservices",
  "Apache Camel": "rpc_and_microservices",
  "Micronaut": "Backend Frameworks",
  "Quarkus": "Backend Frameworks",
  "Vert.x": "rpc_and_microservices",
  "WCF": "rpc_and_microservices",
  "gRPC for .NET": "rpc_and_microservices",
  "gRPC-Go": "rpc_and_microservices",
  "MobX": "state_management",
  "Recoil": "state_management",
  "Redux": "state_management",
  "XState": "state_management",
  "Zustand": "state_management",
  "Air": "cli_and_scripting_tools",
  "Click": "cli_and_scripting_tools",
  "Cobra": "cli_and_scripting_tools",
  "Pest": "cli_and_scripting_tools",
  "Viper": "cli_and_scripting_tools",
  "clap": "cli_and_scripting_tools",
  "nom": "cli_and_scripting_tools",
  "Blade": "templating_engines",
  "Razor Pages": "templating_engines",
  "Smarty": "templating_engines",
  "Twig": "templating_engines",
  "Alpine.js": "Frontend",
  "Angular": "Frontend",
  "Animate.css": "Frontend",
  "Ant Design": "UI/UX Design",
  "Astro": "Frontend",
  "Backbone.js": "Frontend",
  "Bootstrap": "Frontend",
  "Bulma": "Frontend",
  "CSS": "Frontend",
  "CSS Modules": "Frontend",
  "CSS-in-JS": "Frontend",
  "CSShake": "Frontend",
  "Canvas API": "Frontend",
  "Chakra UI": "UI/UX Design",
  "D3.js": "Frontend",
  "Ember.js": "Frontend",
  "Emotion": "Frontend",
  "Foundation": "Frontend",
  "Framer Motion": "Frontend",
  "Greensock (GSAP)": "Frontend",
  "HTML": "Frontend",
  "HTMX": "Frontend",
  "Headless UI": "Frontend",
  "IndexedDB": "Frontend",
  "LESS": "Frontend",
  "Lit": "Frontend",
  "Mantine": "Frontend",
  "Material UI": "Frontend",
  "Motion UI": "Frontend",
  "Next.js": "Frontend",
  "Nuxt.js": "Frontend",
  "PWA": "Frontend",
  "PostCSS": "Frontend",
  "Preact": "Frontend",
  "Qwik": "Frontend",
  "Radix UI": "UI/UX Design",
  "React.js": "Frontend",
  "SVG": "Frontend",
  "Sass": "Frontend",
  "Service Workers": "Frontend",
  "Shadcn/UI": "Frontend",
  "Shoelace": "Frontend",
  "Solid.js": "Frontend",
  "Stencil.js": "Frontend",
  "Stimulus": "Frontend",
  "Styled Components": "Frontend",
  "Svelte": "Frontend",
  "Tailwind CSS": "Frontend",
  "Three.js": "Frontend",
  "Vue.js": "Frontend",
  "Web Audio API": "Frontend",
  "WebAssembly": "Frontend",
  "WebComponents": "Frontend",
  "WebGL": "Frontend",
  "WebGPU": "Frontend",
  "WebRTC": "Frontend",
  "WebSockets": "Frontend",
  "daisyUI": "Frontend",
  "jQuery": "Frontend",
  ".NET Core/.NET 5+": "Backend Frameworks",
  ".NET Framework": "Backend Frameworks",
  "ASP.NET": "Backend Frameworks",
  "Actix (Rust)": "Backend Frameworks",
  "AdonisJS": "Backend Frameworks",
  "Axum (Rust)": "Backend Frameworks",
  "Beego (Go)": "Backend Frameworks",
  "Bun": "Backend Frameworks",
  "CakePHP": "Backend Frameworks",
  "CodeIgniter": "Backend Frameworks",
  "Deno": "Backend Frameworks",
  "Django": "Backend Frameworks",
  "Echo (Go)": "Backend Frameworks",
  "Express.js": "Backend Frameworks",
  "Falcon": "Backend Frameworks",
  "FastAPI": "Backend Frameworks",
  "Fastify": "Backend Frameworks",
  "Feathers": "Backend Frameworks",
  "Fiber (Go)": "Backend Frameworks",
  "Flask": "Backend Frameworks",
  "Gin (Go)": "Backend Frameworks",
  "Grails": "Backend Frameworks",
  "Hanami": "Backend Frameworks",
  "Hapi.js": "Backend Frameworks",
  "Jersey": "Backend Frameworks",
  "Koa.js": "Backend Frameworks",
  "Ktor": "Backend Frameworks",
  "Laravel": "Backend Frameworks",
  "Loopback": "Backend Frameworks",
  "Lumen": "Backend Frameworks",
  "Meteor.js": "Backend Frameworks",
  "Moleculer": "Backend Frameworks",
  "NestJS": "Backend Frameworks",
  "Node.js": "Backend Frameworks",
  "Phalcon": "Backend Frameworks",
  "Phoenix(Elixir)": "Backend Frameworks",
  "Play Framework": "Backend Frameworks",
  "Polka": "Backend Frameworks",
  "Restify": "Backend Frameworks",
  "Rocket(Rust)": "Backend Frameworks",
  "Ruby on Rails": "Backend Frameworks",
  "Sails.js": "Backend Frameworks",
  "Sanic": "Backend Frameworks",
  "Sinatra": "Backend Frameworks",
  "Spring Boot": "Backend Frameworks",
  "Starlette": "Backend Frameworks",
  "Strapi": "Backend Frameworks",
  "Symfony": "Backend Frameworks",
  "Vapor(Swift)": "Backend Frameworks",
  "BaaS": "Tech Stacks",
  "Blitz.js": "Tech Stacks",
  "FEAN": "Tech Stacks",
  "FaaS": "Tech Stacks",
  "Fullstack": "Tech Stacks",
  "JAMstack": "Tech Stacks",
  "LAMP": "Tech Stacks",
  "LEMP": "Tech Stacks",
  "MBaaS": "Tech Stacks",
  "MEAN": "Tech Stacks",
  "MERN": "Tech Stacks",
  "MEVN": "Tech Stacks",
  "PERN": "Tech Stacks",
  "RedwoodJS": "Tech Stacks",
  "Remix.run": "Tech Stacks",
  "SaaS": "Tech Stacks",
  "T3 Stack": "Tech Stacks",
  "TALL Stack": "Tech Stacks",
  "TEAN": "Tech Stacks",
  "VEAN": "Tech Stacks",
  "WASP": "Tech Stacks",
  "WISA": "Tech Stacks",
  "ARKit": "Mobile Development",
  "Android (Java, Kotlin)": "Mobile Development",
  "Android Jetpack": "Mobile Development",
  "CameraX": "Mobile Development",
  "Capacitor.js": "Mobile Development",
  "Compose Multiplatform": "Mobile Development",
  "Core Animation": "Mobile Development",
  "Core Bluetooth": "Mobile Development",
  "Core Data": "Mobile Development",
  "CoreML": "Mobile Development",
  "Flutter": "Mobile Development",
  "In-App Purchases": "Mobile Development",
  "Ionic": "Mobile Development",
  "Jetpack Compose": "Mobile Development",
  "Kotlin Multiplatform": "Mobile Development",
  "Mobile Analytics": "Mobile Development",
  "Mobile Authentication": "Mobile Development",
  "Mobile Payments": "Mobile Development",
  "NativeScript": "Mobile Development",
  "Navigation Component": "Mobile Development",
  "Offline First": "Mobile Development",
  "Progressive Web Apps (PWA)": "Mobile Development",
  "Push Notifications": "Mobile Development",
  "React Native": "Mobile Development",
  "Room": "Mobile Development",
  "RxJava": "Mobile Development",
  "SwiftUI": "Mobile Development",
  "Tauri": "Mobile Development",
  "UIKit": "Mobile Development",
  "WidgetKit": "Mobile Development",
  "WorkManager": "Mobile Development",
  "Xamarin": "Mobile Development",
  "iOS (Swift, Objective-C)": "Mobile Development",
  "Apache Cassandra": "Big Data",
  "Apache HBase": "Big Data",
  "ArangoDB": "Databases",
  "Cassandra": "Databases",
  "Chroma": "Databases",
  "ClickHouse": "Databases",
  "CockroachDB": "Databases",
  "CouchDB": "Databases",
  "Couchbase": "Databases",
  "DataStax Astra": "Databases",
  "Derby": "Databases",
  "Dragonfly": "Databases",
  "DuckDB": "Databases",
  "DynamoDB": "Databases",
  "EdgeDB": "Databases",
  "Elasticsearch": "Databases",
  "FaunaDB": "Databases",
  "Firebase": "Databases",
  "Firebird": "Databases",
  "FoundationDB": "Databases",
  "H2": "Databases",
  "IBM Db2": "Databases",
  "InfluxDB": "Databases",
  "InterBase": "Databases",
  "LanceDB": "Databases",
  "MariaDB": "Databases",
  "Memcached": "Databases",
  "Microsoft SQL Server": "Databases",
  "Milvus": "Databases",
  "MongoDB": "Databases",
  "Mongoose": "Databases",
  "MySQL": "Databases",
  "Neo4j": "Databases",
  "Oracle Database": "Databases",
  "Pinecone": "Databases",
  "PlanetScale": "Databases",
  "PostgreSQL": "Databases",
  "Prisma": "Databases",
  "Qdrant": "Databases",
  "QuestDB": "Databases",
  "RavenDB": "Databases",
  "Redis": "Databases",
  "RethinkDB": "Databases",
  "SAP HANA": "Databases",
  "SQLite": "Databases",
  "SQLite Alternative (SQLite3)": "Databases",
  "ScyllaDB": "Databases",
  "SingleStore": "Databases",
  "Supabase": "Databases",
  "SurrealDB": "Databases",
  "Sybase": "Databases",
  "Teradata": "Databases",
  "TiDB": "Databases",
  "Tigris": "Databases",
  "TimescaleDB": "Databases",
  "Weaviate": "Databases",
  "AKS": "DevOps & Cloud",
  "AWS": "DevOps & Cloud",
  "AWS CDK": "DevOps & Cloud",
  "AWS ECS": "DevOps & Cloud",
  "AWS EKS": "DevOps & Cloud",
  "AWS Lambda": "DevOps & Cloud",
  "AWS SAM": "DevOps & Cloud",
  "Ansible": "DevOps & Cloud",
  "Apache": "System Administration",
  "ArgoCD": "DevOps & Cloud",
  "Artifactory": "DevOps & Cloud",
  "Azure": "DevOps & Cloud",
  "Azure Functions": "DevOps & Cloud",
  "Azure Resource Manager": "DevOps & Cloud",
  "Bamboo": "DevOps & Cloud",
  "Buildkite": "DevOps & Cloud",
  "Chef": "DevOps & Cloud",
  "CircleCI": "DevOps & Cloud",
  "Cloudflare": "DevOps & Cloud",
  "Cloudformation": "DevOps & Cloud",
  "Consul": "DevOps & Cloud",
  "Crossplane": "DevOps & Cloud",
  "DigitalOcean": "DevOps & Cloud",
  "Docker": "DevOps & Cloud",
  "Drone CI": "DevOps & Cloud",
  "ELK Stack": "System Administration",
  "Envoy": "DevOps & Cloud",
  "Fluentd": "DevOps & Cloud",
  "Flux": "DevOps & Cloud",
  "Fly.io": "DevOps & Cloud",
  "GKE": "DevOps & Cloud",
  "GitHub Actions": "DevOps & Cloud",
  "GitLab CI/CD": "DevOps & Cloud",
  "GitOps": "DevOps & Cloud",
  "GoCD": "DevOps & Cloud",
  "Google Cloud": "DevOps & Cloud",
  "Google Cloud Functions": "DevOps & Cloud",
  "Grafana": "System Administration",
  "HAProxy": "DevOps & Cloud",
  "Helm": "DevOps & Cloud",
  "Heroku": "DevOps & Cloud",
  "IBM Cloud": "DevOps & Cloud",
  "Infrastructure as Code (IaC)": "DevOps & Cloud",
  "Istio": "DevOps & Cloud",
  "Jaeger": "DevOps & Cloud",
  "Jenkins": "DevOps & Cloud",
  "Kibana": "DevOps & Cloud",
  "Kong": "DevOps & Cloud",
  "Kubernetes": "DevOps & Cloud",
  "Linode": "DevOps & Cloud",
  "Logstash": "DevOps & Cloud",
  "NGINX": "DevOps & Cloud",
  "Netlify": "DevOps & Cloud",
  "Nexus": "Methodologies & Practices",
  "Nomad": "DevOps & Cloud",
  "OpenShift": "DevOps & Cloud",
  "OpenTelemetry": "DevOps & Cloud",
  "Oracle Cloud": "DevOps & Cloud",
  "Packer": "DevOps & Cloud",
  "Podman": "DevOps & Cloud",
  "Prometheus": "System Administration",
  "Pulumi": "DevOps & Cloud",
  "Puppet": "DevOps & Cloud",
  "Railway": "DevOps & Cloud",
  "Rancher": "DevOps & Cloud",
  "Render": "DevOps & Cloud",
  "SaltStack": "DevOps & Cloud",
  "Serverless Framework": "DevOps & Cloud",
  "Service Mesh": "DevOps & Cloud",
  "Spinnaker": "DevOps & Cloud",
  "TeamCity": "DevOps & Cloud",
  "Terraform": "DevOps & Cloud",
  "Traefik": "DevOps & Cloud",
  "Travis CI": "DevOps & Cloud",
  "Vagrant": "DevOps & Cloud",
  "Vercel": "DevOps & Cloud",
  "Vultr": "DevOps & Cloud",
  "Waypoint": "DevOps & Cloud",
  "Zipkin": "DevOps & Cloud",
  "Azure DevOps": "Version Control",
  "Bitbucket": "Version Control",
  "Conventional Commits": "Version Control",
  "Gerrit": "Version Control",
  "Git": "Version Control",
  "Git Flow": "Version Control",
  "GitHub": "Version Control",
  "GitHub Flow": "Version Control",
  "GitLab": "Version Control",
  "Mercurial": "Version Control",
  "Perforce": "Version Control",
  "SVN": "Version Control",
  "Semantic Versioning": "Version Control",
  "Trunk Based Development": "Version Control",
  "2FA": "Cybersecurity",
  "ABAC": "Cybersecurity",
  "AppSec": "Cybersecurity",
  "Blue Team": "Cybersecurity",
  "Burp Suite": "Cybersecurity",
  "CCSP": "Cybersecurity",
  "CEH": "Cybersecurity",
  "CISM": "Cybersecurity",
  "CISSP": "Cybersecurity",
  "CSRF": "Cybersecurity",
  "Cryptography": "Cybersecurity",
  "DevSecOps": "Cybersecurity",
  "Ethical Hacking": "Cybersecurity",
  "Forensics": "Cybersecurity",
  "GDPR": "Cybersecurity",
  "HIPAA": "Cybersecurity",
  "HSM": "Cybersecurity",
  "IDS/IPS": "Cybersecurity",
  "JWT Authentication": "Cybersecurity",
  "KMS": "Cybersecurity",
  "Kali Linux": "Cybersecurity",
  "MFA": "Cybersecurity",
  "MITRE ATT&CK": "Cybersecurity",
  "Metasploit": "Cybersecurity",
  "Nmap": "Cybersecurity",
  "OAuth 2.0": "Cybersecurity",
  "OSINT": "Cybersecurity",
  "OWASP Top 10": "Cybersecurity",
  "OpenID Connect": "Cybersecurity",
  "PCI-DSS": "Cybersecurity",
  "Passwordless Authentication": "Cybersecurity",
  "Penetration Testing": "Cybersecurity",
  "Purple Team": "Cybersecurity",
  "RBAC": "Cybersecurity",
  "Red Team": "Cybersecurity",
  "Reverse Engineering": "Cybersecurity",
  "SAML": "Cybersecurity",
  "SIEM": "Cybersecurity",
  "SOC": "Cybersecurity",
  "SSL/TLS": "Cybersecurity",
  "SSO": "Cybersecurity",
  "Secure SDLC": "Cybersecurity",
  "Security Architecture": "Cybersecurity",
  "Security Code Review": "Cybersecurity",
  "Security Compliance": "Cybersecurity",
  "Security Fuzzing": "Cybersecurity",
  "Security Hardening": "Cybersecurity",
  "Security Scanning": "Cybersecurity",
  "Snort": "Cybersecurity",
  "Suricata": "Cybersecurity",
  "Threat Modeling": "Cybersecurity",
  "Vulnerability Assessment": "Cybersecurity",
  "Vulnerability Management": "Cybersecurity",
  "WAF": "Cybersecurity",
  "Wireshark": "Cybersecurity",
  "XSS": "Cybersecurity",
  "Zero Trust Architecture": "Cybersecurity",
  "A/B Testing": "Data Science & Analytics",
  "AI Ethics": "AI/ML",
  "AutoML": "AI/ML",
  "BERT": "AI/ML",
  "CLIP": "AI/ML",
  "CUDA": "AI/ML",
  "Computer Vision": "AI/ML",
  "DVC": "AI/ML",
  "DeepSpeed": "AI/ML",
  "Detectron": "AI/ML",
  "Diffusion Models": "AI/ML",
  "Experiment Tracking": "AI/ML",
  "FastAI": "AI/ML",
  "Feature Store": "AI/ML",
  "GPT": "AI/ML",
  "Gensim": "AI/ML",
  "Hugging Face Transformers": "AI/ML",
  "JAX": "AI/ML",
  "Keras": "AI/ML",
  "Kubeflow": "AI/ML",
  "LLM Engineering": "AI/ML",
  "Langchain": "AI/ML",
  "LightGBM": "AI/ML",
  "LlamaIndex": "AI/ML",
  "LoRA": "AI/ML",
  "ML Monitoring": "AI/ML",
  "ML Pipelines": "AI/ML",
  "ML Versioning": "AI/ML",
  "ML.NET": "AI/ML",
  "MLOps": "AI/ML",
  "MLflow": "AI/ML",
  "MXNet": "AI/ML",
  "Matplotlib": "AI/ML",
  "Model Registry": "AI/ML",
  "Model Serving": "AI/ML",
  "Multimodal AI": "AI/ML",
  "NLP": "AI/ML",
  "NumPy": "AI/ML",
  "ONNX": "AI/ML",
  "Object Detection": "AI/ML",
  "OpenAI API": "AI/ML",
  "OpenCV": "AI/ML",
  "PEFT": "AI/ML",
  "Pandas": "AI/ML",
  "Plotly": "AI/ML",
  "Prompt Engineering": "AI/ML",
  "PySpark": "AI/ML",
  "PyTorch": "AI/ML",
  "RLHF": "AI/ML",
  "Ray": "AI/ML",
  "Reinforcement Learning": "AI/ML",
  "Responsible AI": "AI/ML",
  "Roberta": "AI/ML",
  "SciPy": "AI/ML",
  "Scikit-learn": "AI/ML",
  "Seaborn": "AI/ML",
  "Semantic Segmentation": "AI/ML",
  "Stable Diffusion": "AI/ML",
  "T5": "AI/ML",
  "TF Lite": "AI/ML",
  "TensorBoard": "AI/ML",
  "TensorFlow": "AI/ML",
  "Vector Databases": "AI/ML",
  "Weights & Biases": "AI/ML",
  "Whisper AI": "AI/ML",
  "XGBoost": "AI/ML",
  "YOLO": "AI/ML",
  "spaCy": "AI/ML",
  "A-Frame": "Game Development",
  "Amazon Lumberyard": "Game Development",
  "Armory 3D": "Game Development",
  "Babylon.js": "Game Development",
  "Blender Game Engine": "Game Development",
  "Box2D": "Game Development",
  "Buildbox": "Game Development",
  "Bullet Physics": "Game Development",
  "Cocos2d": "Game Development",
  "Construct 3": "Game Development",
  "CryEngine": "Game Development",
  "Defold": "Game Development",
  "DirectX": "Game Development",
  "DragonBones": "Game Development",
  "FMOD": "Game Development",
  "FMod": "Game Development",
  "GLSL": "Game Development",
  "Game AI": "Game Development",
  "Game Analytics": "Game Development",
  "Game Networking": "Game Development",
  "GameMaker Studio": "Game Development",
  "GameSparks": "Game Development",
  "Godot (GDScript)": "Game Development",
  "HLSL": "Game Development",
  "Havok": "Game Development",
  "JMonkeyEngine": "Game Development",
  "LibGDX": "Game Development",
  "Lumberyard": "Game Development",
  "LÖVE (Love2D)": "Game Development",
  "Marmalade": "Game Development",
  "MonoGame": "Game Development",
  "NVIDIA PhysX": "Game Development",
  "OpenGL": "Game Development",
  "Panda3D": "Game Development",
  "Pathfinding": "Game Development",
  "Phaser.js": "Game Development",
  "PixiJS": "Game Development",
  "PlayCanvas": "Game Development",
  "Procedural Generation": "Game Development",
  "Pygame": "Game Development",
  "RPG Maker": "Game Development",
  "Raylib": "Game Development",
  "SDL": "Game Development",
  "SFML": "Game Development",
  "Shaders": "Game Development",
  "Spine": "Game Development",
  "SpriteBatch": "Game Development",
  "Spriter": "Game Development",
  "Stride": "Game Development",
  "Unity (C#)": "Game Development",
  "Unity DOTS": "Game Development",
  "Unreal Engine (C++)": "Game Development",
  "Voxel Engines": "Game Development",
  "Vulkan": "Game Development",
  "Wwise": "Game Development",
  "XNA": "Game Development",
  "p5.js": "Game Development",
  "Algorand": "Blockchain",
  "Aptos": "Blockchain",
  "Arbitrum": "Blockchain",
  "Arweave": "Blockchain",
  "Avalanche": "Blockchain",
  "Aztec": "Blockchain",
  "Binance Smart Chain": "Blockchain",
  "Blockchain Governance": "Blockchain",
  "Cairo": "Blockchain",
  "Cardano": "Blockchain",
  "Chainbridge": "Blockchain",
  "Chainlink": "Blockchain",
  "Conflux": "Blockchain",
  "Corda": "Blockchain",
  "Cosmos SDK": "Blockchain",
  "Cross-Chain Bridges": "Blockchain",
  "DAOs": "Blockchain",
  "DeFi": "Blockchain",
  "EOS": "Blockchain",
  "Ethereum": "Blockchain",
  "Ethers.js": "Blockchain",
  "Filecoin": "Blockchain",
  "Foundry": "Blockchain",
  "Hardhat": "Blockchain",
  "Hedera": "Blockchain",
  "Hyperledger": "Blockchain",
  "IPFS": "Blockchain",
  "Ink! (Polkadot)": "Blockchain",
  "Interledger": "Blockchain",
  "Layer 2 Solutions": "Blockchain",
  "Mina": "Blockchain",
  "NEAR Protocol": "Blockchain",
  "NFTs": "Blockchain",
  "OpenZeppelin": "Blockchain",
  "Optimism": "Blockchain",
  "Oracles": "Blockchain",
  "Polygon": "Blockchain",
  "Rollups": "Blockchain",
  "Rust (for Solana)": "Blockchain",
  "Smart Contracts": "Blockchain",
  "Solana": "Blockchain",
  "StarkNet": "Blockchain",
  "Stellar": "Blockchain",
  "Sui": "Blockchain",
  "Tezos": "Blockchain",
  "The Graph": "Blockchain",
  "Truffle": "Blockchain",
  "Vyper": "Blockchain",
  "Web3.js": "Blockchain",
  "XRPL": "Blockchain",
  "Zero Knowledge Proofs": "Blockchain",
  "zkSync": "Blockchain",
  "ARM Cortex-M": "IoT & Embedded",
  "AVR": "IoT & Embedded",
  "Arduino": "IoT & Embedded",
  "BLE": "IoT & Embedded",
  "Buildroot": "IoT & Embedded",
  "BusyBox": "IoT & Embedded",
  "CAN Bus": "IoT & Embedded",
  "CircuitPython": "IoT & Embedded",
  "Contiki": "IoT & Embedded",
  "DALI": "IoT & Embedded",
  "DDS": "IoT & Embedded",
  "Digital Twin": "IoT & Embedded",
  "ESP32": "IoT & Embedded",
  "ESP8266": "IoT & Embedded",
  "ESPHome": "IoT & Embedded",
  "EdgeX Foundry": "IoT & Embedded",
  "Embedded C": "IoT & Embedded",
  "Embedded Linux": "IoT & Embedded",
  "EnOcean": "IoT & Embedded",
  "FreeRTOS": "IoT & Embedded",
  "Home Assistant": "IoT & Embedded",
  "Industrial IoT": "IoT & Embedded",
  "IoT Analytics": "IoT & Embedded",
  "IoT Security": "IoT & Embedded",
  "KNX": "IoT & Embedded",
  "LoRaWAN": "IoT & Embedded",
  "MQTT": "IoT & Embedded",
  "Matter Protocol": "IoT & Embedded",
  "Mbed OS": "IoT & Embedded",
  "MicroPython": "IoT & Embedded",
  "Modbus": "IoT & Embedded",
  "Nordic nRF": "IoT & Embedded",
  "NuttX": "IoT & Embedded",
  "OPC Classic": "IoT & Embedded",
  "OPC-UA": "IoT & Embedded",
  "OpenThread": "IoT & Embedded",
  "OpenWrt": "IoT & Embedded",
  "PlatformIO": "IoT & Embedded",
  "RIOT OS": "IoT & Embedded",
  "RTOS": "IoT & Embedded",
  "Raspberry Pi": "IoT & Embedded",
  "SCADA": "IoT & Embedded",
  "STM32": "IoT & Embedded",
  "Tasmota": "IoT & Embedded",
  "Texas Instruments MSP430": "IoT & Embedded",
  "ThingsBoard": "IoT & Embedded",
  "Thread": "IoT & Embedded",
  "TinyML": "IoT & Embedded",
  "Yocto Project": "IoT & Embedded",
  "Z-Wave": "IoT & Embedded",
  "Zephyr OS": "IoT & Embedded",
  "Zigbee": "IoT & Embedded",
  "uClibc": "IoT & Embedded",
  "Accessibility Testing": "Testing",
  "Allure": "Testing",
  "Appium": "Testing",
  "Artillery": "Testing",
  "BackstopJS": "Testing",
  "Behave": "Testing",
  "BrowserStack": "Testing",
  "Calabash": "Testing",
  "Canary Testing": "Testing",
  "Capybara": "Testing",
  "Cucumber": "Testing",
  "Cypress": "Testing",
  "Espresso": "Testing",
  "Gatling": "Testing",
  "Gauge": "Testing",
  "JMeter": "Testing",
  "JMockit": "Testing",
  "JUnit": "Testing",
  "Jasmine": "Testing",
  "Jest": "Testing",
  "K6": "Testing",
  "Karate DSL": "Testing",
  "Karma": "Testing",
  "LambdaTest": "Testing",
  "Load Testing": "Testing",
  "Locust": "Testing",
  "MSTest": "Testing",
  "Minitest": "Testing",
  "Mocha": "Testing",
  "Mock Service Worker (MSW)": "Testing",
  "NUnit": "Testing",
  "Nightwatch.js": "Testing",
  "Performance Testing": "Testing",
  "Playwright": "Testing",
  "Postman": "Testing",
  "Protractor": "Testing",
  "Puppeteer": "Testing",
  "PyTest": "Testing",
  "Pytest": "Testing",
  "Pytest-BDD": "Testing",
  "RSpec": "Testing",
  "RTL": "Testing",
  "Ranorex": "Testing",
  "RestAssured": "Testing",
  "Robot Framework": "Testing",
  "Sauce Labs": "Testing",
  "Security Testing": "Testing",
  "Selenium": "Testing",
  "SoapUI": "Testing",
  "Specflow": "Testing",
  "Storybook": "UI/UX Design",
  "Stress Testing": "Testing",
  "Supertest": "Testing",
  "TestComplete": "Testing",
  "TestNG": "Testing",
  "Testing Library": "Testing",
  "UIAutomator": "Testing",
  "User Acceptance Testing(UAT)": "Testing",
  "Vitest": "Testing",
  "WebdriverIO": "Testing",
  "XCTest": "Testing",
  "go-sqlmock": "Testing",
  "gomock": "Testing",
  "testify": "Testing",
  "xUnit": "Testing",
  "Active Directory": "System Administration",
  "AppArmor": "System Administration",
  "BGP": "System Administration",
  "Backup Systems": "System Administration",
  "Bash Scripting": "System Administration",
  "Clustering": "Data Science & Analytics",
  "Cron Jobs": "System Administration",
  "DHCP": "System Administration",
  "DNS": "System Administration",
  "Datadog": "System Administration",
  "Disaster Recovery": "System Administration",
  "Domain Controllers": "System Administration",
  "Email Servers": "System Administration",
  "File Servers": "System Administration",
  "Firewall Configuration": "System Administration",
  "Graylog": "System Administration",
  "HTTP/HTTPS": "System Administration",
  "High Availability": "System Administration",
  "Hyper-V": "System Administration",
  "Incident Response": "System Administration",
  "LDAP": "System Administration",
  "Linux Administration": "System Administration",
  "Load Balancing": "System Administration",
  "Log Rotation": "System Administration",
  "Nagios": "System Administration",
  "Network Monitoring": "System Administration",
  "Network Troubleshooting": "System Administration",
  "New Relic": "System Administration",
  "Nginx": "System Administration",
  "PagerDuty": "System Administration",
  "Print Servers": "System Administration",
  "Proxmox": "System Administration",
  "RAID": "System Administration",
  "SELinux": "System Administration",
  "SRE Practices": "System Administration",
  "SSH": "System Administration",
  "Splunk": "System Administration",
  "Storage Systems": "System Administration",
  "Systemd": "System Administration",
  "TCP/IP": "System Administration",
  "VMware": "System Administration",
  "VPN Configuration": "System Administration",
  "Web Servers": "System Administration",
  "Windows Server": "System Administration",
  "WireGuard": "System Administration",
  "Zabbix": "System Administration",
  "iptables": "System Administration",
  "Adobe XD": "UI/UX Design",
  "Atomic Design": "UI/UX Design",
  "Balsamiq": "UI/UX Design",
  "Bootstrap UI": "UI/UX Design",
  "Carbon Design System": "UI/UX Design",
  "Color Theory": "UI/UX Design",
  "Conversational UI": "UI/UX Design",
  "Dark Mode": "UI/UX Design",
  "Design Psychology": "UI/UX Design",
  "Design Research": "UI/UX Design",
  "Design Systems": "UI/UX Design",
  "Design Thinking": "UI/UX Design",
  "Design Tokens": "UI/UX Design",
  "Figma": "UI/UX Design",
  "Figma Plugins": "UI/UX Design",
  "Flat Design": "UI/UX Design",
  "Framer": "UI/UX Design",
  "Gamification": "UI/UX Design",
  "Glassmorphism": "UI/UX Design",
  "Heuristic Evaluation": "UI/UX Design",
  "Icon Design": "UI/UX Design",
  "InVision": "UI/UX Design",
  "Information Architecture": "UI/UX Design",
  "Interaction Design": "UI/UX Design",
  "MUI (Material UI)": "UI/UX Design",
  "Material Design": "UI/UX Design",
  "Micro Interactions": "UI/UX Design",
  "Mobile-First Design": "UI/UX Design",
  "Motion Design": "UI/UX Design",
  "Neumorphism": "UI/UX Design",
  "Prototyping": "UI/UX Design",
  "Responsive Design": "UI/UX Design",
  "Sketch": "UI/UX Design",
  "Skeuomorphism": "UI/UX Design",
  "Tailwind UI": "UI/UX Design",
  "Typography": "UI/UX Design",
  "UX Writing": "UI/UX Design",
  "Usability Testing": "UI/UX Design",
  "User Journeys": "UI/UX Design",
  "User Personas": "UI/UX Design",
  "User Research": "UI/UX Design",
  "Voice UI": "UI/UX Design",
  "WCAG Accessibility": "UI/UX Design",
  "Wireframing": "UI/UX Design",
  "12 Factor App": "Methodologies & Practices",
  "API-First Development": "Methodologies & Practices",
  "Agile": "Methodologies & Practices",
  "Backlog Refinement": "Methodologies & Practices",
  "Behavior-Driven Development (BDD)": "Methodologies & Practices",
  "Burndown Charts": "Methodologies & Practices",
  "CI/CD": "Methodologies & Practices",
  "CQRS": "Methodologies & Practices",
  "Clean Code": "Methodologies & Practices",
  "Code Reviews": "Methodologies & Practices",
  "Continuous Discovery": "Methodologies & Practices",
  "Design Patterns": "Methodologies & Practices",
  "DevOps": "Methodologies & Practices",
  "Disciplined Agile": "Methodologies & Practices",
  "Domain-Driven Design (DDD)": "Methodologies & Practices",
  "Event Sourcing": "Methodologies & Practices",
  "Event-Driven Architecture": "Methodologies & Practices",
  "Feature-Driven Development (FDD)": "Methodologies & Practices",
  "Hexagonal Architecture": "Methodologies & Practices",
  "Impact Mapping": "Methodologies & Practices",
  "Jobs-to-be-Done": "Methodologies & Practices",
  "KPIs": "Methodologies & Practices",
  "Kanban": "Methodologies & Practices",
  "LeSS": "Methodologies & Practices",
  "Lean UX": "Methodologies & Practices",
  "Microservices Architecture": "Methodologies & Practices",
  "Mob Programming": "Methodologies & Practices",
  "Monorepo": "Methodologies & Practices",
  "OKRs": "Methodologies & Practices",
  "Pair Programming": "Methodologies & Practices",
  "Refactoring": "Methodologies & Practices",
  "Retrospectives": "Methodologies & Practices",
  "SAFe": "Methodologies & Practices",
  "SOLID Principles": "Methodologies & Practices",
  "Scrum": "Methodologies & Practices",
  "Serverless Architecture": "Methodologies & Practices",
  "Shape Up": "Methodologies & Practices",
  "Sprint Planning": "Methodologies & Practices",
  "Standup Meetings": "Methodologies & Practices",
  "Story Mapping": "Methodologies & Practices",
  "Technical Debt Management": "Methodologies & Practices",
  "Test-Driven Development (TDD)": "Methodologies & Practices",
  "Value Stream Mapping": "Methodologies & Practices",
  "Velocity Tracking": "Methodologies & Practices",
  "Waterfall": "Methodologies & Practices",
  "XP (Extreme Programming)": "Methodologies & Practices",
  "Amazon Redshift": "Big Data",
  "Apache Airflow": "Big Data",
  "Apache Beam": "Big Data",
  "Apache Druid": "Big Data",
  "Apache Flink": "Big Data",
  "Apache Hadoop": "Big Data",
  "Apache Hive": "Big Data",
  "Apache Iceberg": "Big Data",
  "Apache Kafka": "Big Data",
  "Apache Kylin": "Big Data",
  "Apache NiFi": "Big Data",
  "Apache Pinot": "Big Data",
  "Apache Pulsar": "Big Data",
  "Apache Spark": "Big Data",
  "Apache Storm": "Big Data",
  "Avro": "Big Data",
  "Batch Processing": "Big Data",
  "Business Intelligence": "Data Science & Analytics",
  "Data Catalog": "Big Data",
  "Data Governance": "Big Data",
  "Data Ingestion": "Big Data",
  "Data Lakes": "Big Data",
  "Data Lineage": "Big Data",
  "Data Mesh": "Big Data",
  "Data Modeling": "Data Science & Analytics",
  "Data Pipelines": "Big Data",
  "Data Quality": "Big Data",
  "Data Visualization": "Data Science & Analytics",
  "Data Warehousing": "Big Data",
  "Databricks": "Big Data",
  "Delta Lake": "Big Data",
  "ETL / ELT": "Big Data",
  "Google BigQuery": "Big Data",
  "JSON": "Big Data",
  "Looker": "Big Data",
  "MapReduce": "Big Data",
  "Master Data Management": "Big Data",
  "OLAP": "Big Data",
  "OLTP": "Big Data",
  "ORC": "Big Data",
  "Parquet": "Big Data",
  "Power BI": "Low-Code/No-Code",
  "Presto": "Big Data",
  "Protobuf": "Big Data",
  "Snowflake": "Big Data",
  "Stream Processing": "Big Data",
  "Tableau": "Big Data",
  "Thrift": "Big Data",
  "Trino": "Big Data",
  "dbt": "Big Data",
  "Adalo": "Low-Code/No-Code",
  "Airtable": "Low-Code/No-Code",
  "AppGyver": "Low-Code/No-Code",
  "AppSheet": "Low-Code/No-Code",
  "Appian": "Low-Code/No-Code",
  "Bubble": "Low-Code/No-Code",
  "Coda": "Low-Code/No-Code",
  "Fibery": "Low-Code/No-Code",
  "Glide": "Low-Code/No-Code",
  "Internal.io": "Low-Code/No-Code",
  "Make (Integromat)": "Low-Code/No-Code",
  "Mendix": "Low-Code/No-Code",
  "Microsoft Power Platform": "Low-Code/No-Code",
  "Notion": "Low-Code/No-Code",
  "Oracle APEX": "Low-Code/No-Code",
  "OutSystems": "Low-Code/No-Code",
  "Power Apps": "Low-Code/No-Code",
  "Power Automate": "Low-Code/No-Code",
  "Retool": "Low-Code/No-Code",
  "Salesforce Platform": "Low-Code/No-Code",
  "ServiceNow": "Low-Code/No-Code",
  "Softr": "Low-Code/No-Code",
  "Tray.io": "Low-Code/No-Code",
  "UI Bakery": "Low-Code/No-Code",
  "Webflow": "Low-Code/No-Code",
  "Workato": "Low-Code/No-Code",
  "Zapier": "Low-Code/No-Code",
  "n8n": "Low-Code/No-Code",
  "Accountability": "Soft Skills",
  "Active Listening": "Soft Skills",
  "Adaptability": "Soft Skills",
  "Agility": "Soft Skills",
  "Business Acumen": "Soft Skills",
  "Coaching": "Soft Skills",
  "Collaboration": "Soft Skills",
  "Communication": "Soft Skills",
  "Conflict Resolution": "Soft Skills",
  "Continuous Learning": "Soft Skills",
  "Creativity": "Soft Skills",
  "Critical Thinking": "Soft Skills",
  "Cross-Cultural Communication": "Soft Skills",
  "Customer Service": "Soft Skills",
  "Decision Making": "Soft Skills",
  "Documentation": "Soft Skills",
  "Emotional Intelligence": "Soft Skills",
  "Empathy": "Soft Skills",
  "Feedback Giving & Receiving": "Soft Skills",
  "Leadership": "Soft Skills",
  "Meeting Facilitation": "Soft Skills",
  "Mentorship": "Soft Skills",
  "Negotiation": "Soft Skills",
  "Presentation Skills": "Soft Skills",
  "Problem-Solving": "Soft Skills",
  "Project Management": "Soft Skills",
  "Public Speaking": "Soft Skills",
  "Remote Work": "Soft Skills",
  "Resilience": "Soft Skills",
  "Self-Motivation": "Soft Skills",
  "Stakeholder Management": "Soft Skills",
  "Strategic Thinking": "Soft Skills",
  "Stress Management": "Soft Skills",
  "Teamwork": "Soft Skills",
  "Technical Writing": "Soft Skills",
  "Time Management": "Soft Skills",
  "Work-Life Balance": "Soft Skills",
  "Anomaly Detection": "Data Science & Analytics",
  "Churn Prediction": "Data Science & Analytics",
  "Classification": "Data Science & Analytics",
  "Cohort Analysis": "Data Science & Analytics",
  "Customer Segmentation": "Data Science & Analytics",
  "Dashboard Design": "Data Science & Analytics",
  "Data Analysis": "Data Science & Analytics",
  "Data Cleaning": "Data Science & Analytics",
  "Data Transformation": "Data Science & Analytics",
  "Database Optimization": "Data Science & Analytics",
  "Descriptive Analytics": "Data Science & Analytics",
  "Diagnostic Analytics": "Data Science & Analytics",
  "Dimensionality Reduction": "Data Science & Analytics",
  "ETL Processes": "Data Science & Analytics",
  "Financial Modeling": "Data Science & Analytics",
  "Forecasting": "Data Science & Analytics",
  "Funnel Analysis": "Data Science & Analytics",
  "Hypothesis Testing": "Data Science & Analytics",
  "Market Basket Analysis": "Data Science & Analytics",
  "Natural Language Processing": "Data Science & Analytics",
  "Predictive Analytics": "Data Science & Analytics",
  "Prescriptive Analytics": "Data Science & Analytics",
  "Regression Analysis": "Data Science & Analytics",
  "Reporting": "Data Science & Analytics",
  "Retention Analysis": "Data Science & Analytics",
  "Sentiment Analysis": "Data Science & Analytics",
  "Statistical Analysis": "Data Science & Analytics",
  "Text Mining": "Data Science & Analytics",
  "Time Series Analysis": "Data Science & Analytics",
  "Web Scraping": "Data Science & Analytics"
};

module.exports = skillToCategory;