const softwareEngineeringSkills = {
    'Programming Languages': ['ABAP', 'APL', 'ActionScript', 'Ada', 'Apex', 'Assembly', 'Ballerina', 'Bash', 'C', 'C#', 'C++', 'COBOL', 'COBOL', 'Carbon', 'Ceylon', 'Clojure', 'Crystal', 'D', 'Dart', 'Delphi', 'Eiffel', 'Elixir', 'Elm', 'Erlang', 'F#', 'Forth', 'Fortran', 'Go', 'GraphQL', 'Groovy', 'Hack', 'Haskell', 'J', 'Java', 'JavaScript', 'Julia', 'Kotlin', 'Lisp', 'Lua', 'MATLAB', 'Nim', 'OCaml', 'Objective-C', 'Octave', 'PHP', 'PL/SQL', 'Pascal', 'Perl', 'Pony', 'PowerShell', 'Prolog', 'PureScript', 'Python', 'Q#', 'R', 'RPG', 'Racket', 'ReScript', 'Reason', 'Ruby', 'Rust', 'SAS', 'SQL', 'Scala', 'Scheme', 'Smalltalk', 'Solidity', 'Standard ML', 'Swift', 'T-SQL', 'Tcl', 'TypeScript', 'V', 'VBA', 'VHDL', 'Verilog', 'Visual Basic', 'Zig'],

    'Database ORMs': ['ActiveRecord', 'Alembic', 'Dapper', 'Diesel', 'Doctrine ORM', 'Entity Framework', 'GORM', 'Hibernate', 'JPA', 'Knex.js', 'NHibernate', 'SQLAlchemy', 'Sequelize', 'TypeORM', 'sqlx'],

    'rpc_and_microservices': ['Akka.NET', 'Apache Camel', 'Micronaut', 'Quarkus', 'Vert.x', 'WCF', 'gRPC for .NET', 'gRPC-Go'],

    'state_management': ['MobX', 'Recoil', 'Redux', 'XState', 'Zustand'],

    'cli_and_scripting_tools': ['Air', 'Click', 'Cobra', 'Pest', 'Viper', 'clap', 'nom'],

    'templating_engines': ['Blade', 'Razor Pages', 'Smarty', 'Twig'],

    'Frontend': ['Alpine.js', 'Angular', 'Animate.css', 'Ant Design', 'Astro', 'Backbone.js', 'Bootstrap', 'Bulma', 'CSS', 'CSS Modules', 'CSS-in-JS', 'CSShake', 'Canvas API', 'Chakra UI', 'D3.js', 'Ember.js', 'Emotion', 'Foundation', 'Framer Motion', 'Greensock (GSAP)', 'HTML', 'HTMX', 'Headless UI', 'IndexedDB', 'LESS', 'Lit', 'Mantine', 'Material UI', 'Motion UI', 'Next.js', 'Nuxt.js', 'PWA', 'PostCSS', 'Preact', 'Qwik', 'Radix UI', 'React.js', 'SVG', 'Sass', 'Service Workers', 'Shadcn/UI', 'Shoelace', 'Solid.js', 'Stencil.js', 'Stimulus', 'Styled Components', 'Svelte', 'Tailwind CSS', 'Three.js', 'Vue.js', 'Web Audio API', 'WebAssembly', 'WebComponents', 'WebGL', 'WebGPU', 'WebRTC', 'WebSockets', 'daisyUI', 'jQuery'],

    'Backend': ['.NET Core/.NET 5+', '.NET Framework', 'ASP.NET', 'Actix (Rust)', 'AdonisJS', 'Axum (Rust)', 'Beego (Go)', 'Bun', 'CakePHP', 'CodeIgniter', 'Deno', 'Django', 'Echo (Go)', 'Express.js', 'Falcon', 'FastAPI', 'Fastify', 'Feathers', 'Fiber (Go)', 'Flask', 'Gin (Go)', 'Grails', 'Hanami', 'Hapi.js', 'Jersey', 'Koa.js', 'Ktor', 'Laravel', 'Loopback', 'Lumen', 'Meteor.js', 'Micronaut', 'Moleculer', 'NestJS', 'Node.js', 'Phalcon', 'Phoenix(Elixir)', 'Play Framework', 'Polka', 'Quarkus', 'Restify', 'Rocket(Rust)', 'Ruby on Rails', 'Sails.js', 'Sanic', 'Sinatra', 'Spring Boot', 'Starlette', 'Strapi', 'Symfony', 'Vapor(Swift)'],

    'Tech Stacks': ['BaaS', 'Blitz.js', 'FEAN', 'FaaS', 'Fullstack', 'JAMstack', 'LAMP', 'LEMP', 'MBaaS', 'MEAN', 'MERN', 'MEVN', 'PERN', 'RedwoodJS', 'Remix.run', 'SaaS', 'T3 Stack', 'TALL Stack', 'TEAN', 'VEAN', 'WASP', 'WISA'],

    'Mobile Development': ['ARKit', 'Android (Java, Kotlin)', 'Android Jetpack', 'CameraX', 'Capacitor.js', 'Compose Multiplatform', 'Core Animation', 'Core Bluetooth', 'Core Data', 'CoreML', 'Flutter', 'In-App Purchases', 'Ionic', 'Jetpack Compose', 'Kotlin Multiplatform', 'Mobile Analytics', 'Mobile Authentication', 'Mobile Payments', 'NativeScript', 'Navigation Component', 'Offline First', 'Progressive Web Apps (PWA)', 'Push Notifications', 'React Native', 'Room', 'RxJava', 'SwiftUI', 'Tauri', 'UIKit', 'WidgetKit', 'WorkManager', 'Xamarin', 'iOS (Swift, Objective-C)'],

    'Databases': ['Apache Cassandra', 'Apache HBase', 'ArangoDB', 'Cassandra', 'Chroma', 'ClickHouse', 'CockroachDB', 'CouchDB', 'Couchbase', 'DataStax Astra', 'Derby', 'Dragonfly', 'DuckDB', 'DynamoDB', 'EdgeDB', 'Elasticsearch', 'FaunaDB', 'Firebase', 'Firebird', 'FoundationDB', 'GORM', 'H2', 'Hibernate', 'IBM Db2', 'InfluxDB', 'InterBase', 'LanceDB', 'MariaDB', 'Memcached', 'Microsoft SQL Server', 'Milvus', 'MongoDB', 'Mongoose', 'MySQL', 'Neo4j', 'Oracle Database', 'Pinecone', 'PlanetScale', 'PostgreSQL', 'Prisma', 'Qdrant', 'QuestDB', 'RavenDB', 'Redis', 'RethinkDB', 'SAP HANA', 'SQL', 'SQLite', 'SQLite Alternative (SQLite3)', 'ScyllaDB', 'Sequelize', 'SingleStore', 'Supabase', 'SurrealDB', 'Sybase', 'Teradata', 'TiDB', 'Tigris', 'TimescaleDB', 'TypeORM', 'Weaviate'],

    'DevOps & Cloud': ['AKS', 'AWS', 'AWS CDK', 'AWS ECS', 'AWS EKS', 'AWS Lambda', 'AWS SAM', 'Ansible', 'Apache', 'ArgoCD', 'Artifactory', 'Azure', 'Azure Functions', 'Azure Resource Manager', 'Bamboo', 'Buildkite', 'Chef', 'CircleCI', 'Cloudflare', 'Cloudformation', 'Consul', 'Crossplane', 'DigitalOcean', 'Docker', 'Drone CI', 'ELK Stack', 'Envoy', 'Fluentd', 'Flux', 'Fly.io', 'GKE', 'GitHub Actions', 'GitLab CI/CD', 'GitOps', 'GoCD', 'Google Cloud', 'Google Cloud Functions', 'Grafana', 'HAProxy', 'Helm', 'Heroku', 'IBM Cloud', 'Infrastructure as Code (IaC)', 'Istio', 'Jaeger', 'Jenkins', 'Kibana', 'Kong', 'Kubernetes', 'Linode', 'Logstash', 'NGINX', 'Netlify', 'Nexus', 'Nomad', 'OpenShift', 'OpenTelemetry', 'Oracle Cloud', 'Packer', 'Podman', 'Prometheus', 'Pulumi', 'Puppet', 'Railway', 'Rancher', 'Render', 'SaltStack', 'Serverless Framework', 'Service Mesh', 'Spinnaker', 'TeamCity', 'Terraform', 'Traefik', 'Travis CI', 'Vagrant', 'Vercel', 'Vultr', 'Waypoint', 'Zipkin'],

    'Version Control': ['Azure DevOps', 'Bitbucket', 'Conventional Commits', 'Gerrit', 'Git', 'Git Flow', 'GitHub', 'GitHub Flow', 'GitLab', 'Mercurial', 'Perforce', 'SVN', 'Semantic Versioning', 'Trunk Based Development'],

    'Cybersecurity': ['2FA', 'ABAC', 'AppSec', 'Blue Team', 'Burp Suite', 'CCSP', 'CEH', 'CISM', 'CISSP', 'CSRF', 'Cryptography', 'DevSecOps', 'Ethical Hacking', 'Forensics', 'GDPR', 'HIPAA', 'HSM', 'IDS/IPS', 'JWT Authentication', 'KMS', 'Kali Linux', 'MFA', 'MITRE ATT&CK', 'Metasploit', 'Nmap', 'OAuth 2.0', 'OSINT', 'OWASP Top 10', 'OpenID Connect', 'PCI-DSS', 'Passwordless Authentication', 'Penetration Testing', 'Penetration Testing', 'Purple Team', 'RBAC', 'Red Team', 'Reverse Engineering', 'SAML', 'SIEM', 'SOC', 'SSL/TLS', 'SSO', 'Secure SDLC', 'Security Architecture', 'Security Code Review', 'Security Compliance', 'Security Fuzzing', 'Security Hardening', 'Security Scanning', 'Snort', 'Suricata', 'Threat Modeling', 'Vulnerability Assessment', 'Vulnerability Management', 'WAF', 'Wireshark', 'XSS', 'Zero Trust Architecture'],

    'AI/ML': ['AI Ethics', 'AutoML', 'BERT', 'CLIP', 'CUDA', 'Computer Vision', 'DVC', 'DeepSpeed', 'Detectron', 'Diffusion Models', 'Experiment Tracking', 'FastAI', 'Feature Store', 'GPT', 'Gensim', 'Hugging Face Transformers', 'JAX', 'Keras', 'Kubeflow', 'LLM Engineering', 'Langchain', 'LightGBM', 'LlamaIndex', 'LoRA', 'ML Monitoring', 'ML Pipelines', 'ML Versioning', 'ML.NET', 'MLOps', 'MLflow', 'MXNet', 'Matplotlib', 'Model Registry', 'Model Serving', 'Multimodal AI', 'NLP', 'NumPy', 'ONNX', 'Object Detection', 'OpenAI API', 'OpenCV', 'PEFT', 'Pandas', 'Plotly', 'Prompt Engineering', 'PySpark', 'PyTorch', 'RLHF', 'Ray', 'Reinforcement Learning', 'Responsible AI', 'Roberta', 'SciPy', 'Scikit-learn', 'Seaborn', 'Semantic Segmentation', 'Stable Diffusion', 'T5',
        'TF Lite', 'TensorBoard', 'TensorFlow', 'Vector Databases', 'Weights & Biases', 'Whisper AI', 'XGBoost', 'YOLO', 'spaCy'],

    'Game Development': ['A-Frame', 'Amazon Lumberyard', 'Armory 3D', 'Babylon.js', 'Blender Game Engine', 'Box2D', 'Buildbox', 'Bullet Physics', 'Cocos2d', 'Construct 3', 'CryEngine', 'Defold', 'DirectX', 'DragonBones', 'FMOD', 'FMod', 'GLSL', 'Game AI', 'Game Analytics', 'Game Networking', 'GameMaker Studio', 'GameSparks', 'Godot (GDScript)', 'HLSL', 'Havok', 'JMonkeyEngine', 'LibGDX', 'Lumberyard', 'LÖVE (Love2D)', 'Marmalade', 'MonoGame', 'NVIDIA PhysX', 'OpenGL', 'Panda3D', 'Pathfinding', 'Phaser.js', 'PixiJS', 'PlayCanvas', 'Procedural Generation', 'Pygame', 'RPG Maker', 'Raylib', 'SDL', 'SFML', 'Shaders', 'Spine', 'SpriteBatch', 'Spriter', 'Stride', 'Unity (C#)', 'Unity DOTS', 'Unreal Engine (C++)', 'Voxel Engines', 'Vulkan', 'Wwise', 'XNA', 'p5.js'],

    'Blockchain': ['Algorand', 'Aptos', 'Arbitrum', 'Arweave', 'Avalanche', 'Aztec', 'Binance Smart Chain', 'Blockchain Governance', 'Cairo', 'Cardano', 'Chainbridge', 'Chainlink', 'Conflux', 'Corda', 'Cosmos SDK', 'Cross-Chain Bridges', 'DAOs', 'DeFi', 'EOS', 'Ethereum', 'Ethers.js', 'Filecoin', 'Foundry', 'Hardhat', 'Hedera', 'Hyperledger', 'IPFS', 'Ink! (Polkadot)', 'Interledger', 'Layer 2 Solutions', 'Mina', 'NEAR Protocol', 'NFTs', 'OpenZeppelin', 'Optimism', 'Oracles', 'Polygon', 'Rollups', 'Rust (for Solana)', 'Smart Contracts', 'Solana', 'Solidity', 'StarkNet', 'Stellar', 'Sui', 'Tezos', 'The Graph', 'Truffle', 'Vyper', 'Web3.js', 'XRPL', 'Zero Knowledge Proofs', 'zkSync'],

    'IoT & Embedded': ['ARM Cortex-M', 'AVR', 'Arduino', 'BLE', 'Buildroot', 'BusyBox', 'CAN Bus', 'CircuitPython', 'Contiki', 'DALI', 'DDS', 'Digital Twin', 'ESP32', 'ESP8266', 'ESPHome', 'EdgeX Foundry', 'Embedded C', 'Embedded Linux', 'EnOcean', 'FreeRTOS', 'Home Assistant', 'Industrial IoT', 'IoT Analytics', 'IoT Security', 'KNX', 'LoRaWAN', 'MQTT', 'Matter Protocol', 'Mbed OS', 'MicroPython', 'Modbus', 'Nordic nRF', 'NuttX', 'OPC Classic', 'OPC-UA', 'OpenThread', 'OpenWrt', 'PlatformIO', 'RIOT OS', 'RTOS', 'Raspberry Pi', 'SCADA', 'STM32', 'Tasmota', 'Texas Instruments MSP430', 'ThingsBoard', 'Thread', 'TinyML', 'Yocto Project', 'Z-Wave', 'Zephyr OS', 'Zigbee', 'uClibc'],

    'Testing': ['A/B Testing', 'Accessibility Testing', 'Allure', 'Appium', 'Artillery', 'BackstopJS', 'Behave', 'BrowserStack', 'Calabash', 'Canary Testing', 'Capybara', 'Cucumber', 'Cypress', 'Espresso', 'Gatling', 'Gauge', 'JMeter', 'JMockit', 'JUnit', 'Jasmine', 'Jest', 'K6', 'Karate DSL', 'Karma', 'LambdaTest', 'Load Testing', 'Locust', 'MSTest', 'Minitest', 'Mocha', 'Mock Service Worker (MSW)', 'NUnit', 'Nightwatch.js', 'Performance Testing', 'Playwright', 'Postman', 'Protractor', 'Puppeteer', 'PyTest', 'Pytest', 'Pytest-BDD', 'RSpec', 'RTL', 'Ranorex', 'RestAssured', 'Robot Framework', 'Sauce Labs', 'Security Testing', 'Selenium', 'SoapUI', 'Specflow', 'Storybook', 'Stress Testing', 'Supertest', 'TestComplete', 'TestNG', 'Testing Library', 'UIAutomator', 'User Acceptance Testing(UAT)', 'Vitest', 'WebdriverIO', 'XCTest', 'go-sqlmock', 'gomock', 'testify', 'xUnit'],

    'System Administration': ['Active Directory', 'Apache', 'AppArmor', 'BGP', 'Backup Systems', 'Bash Scripting', 'Clustering', 'Cron Jobs', 'DHCP', 'DNS', 'Datadog', 'Disaster Recovery', 'Domain Controllers', 'ELK Stack', 'Email Servers', 'File Servers', 'Firewall Configuration', 'Grafana', 'Graylog', 'HTTP/HTTPS', 'High Availability', 'Hyper-V', 'Incident Response', 'LDAP', 'Linux Administration', 'Load Balancing', 'Load Balancing', 'Log Rotation', 'Nagios', 'Network Monitoring', 'Network Troubleshooting', 'New Relic', 'Nginx', 'PagerDuty', 'PowerShell', 'Print Servers', 'Prometheus', 'Proxmox', 'RAID', 'SELinux', 'SRE Practices', 'SSH', 'Splunk', 'Storage Systems', 'Systemd', 'TCP/IP', 'VMware', 'VPN Configuration', 'Web Servers', 'Windows Server', 'WireGuard', 'Zabbix', 'iptables'],

    'UI/UX Design': ['Adobe XD', 'Ant Design', 'Atomic Design', 'Balsamiq', 'Bootstrap UI', 'Carbon Design System', 'Chakra UI', 'Color Theory', 'Conversational UI', 'Dark Mode', 'Design Psychology', 'Design Research', 'Design Systems', 'Design Thinking', 'Design Tokens', 'Figma', 'Figma Plugins', 'Flat Design', 'Framer', 'Gamification', 'Glassmorphism', 'Heuristic Evaluation', 'Icon Design', 'InVision', 'Information Architecture', 'Interaction Design', 'MUI (Material UI)', 'Material Design', 'Micro Interactions', 'Mobile-First Design', 'Motion Design', 'Neumorphism', 'Prototyping', 'Radix UI', 'Responsive Design', 'Sketch', 'Skeuomorphism', 'Storybook', 'Tailwind UI', 'Typography', 'UX Writing', 'Usability Testing', 'User Journeys', 'User Personas', 'User Research', 'Voice UI', 'WCAG Accessibility', 'Wireframing'],

    'Methodologies & Practices': ['12 Factor App', 'API-First Development', 'Agile', 'Backlog Refinement', 'Behavior-Driven Development (BDD)', 'Burndown Charts', 'CI/CD', 'CQRS', 'Clean Code', 'Code Reviews', 'Continuous Discovery', 'Design Patterns', 'DevOps', 'Disciplined Agile', 'Domain-Driven Design (DDD)', 'Event Sourcing', 'Event-Driven Architecture', 'Feature-Driven Development (FDD)', 'Hexagonal Architecture', 'Impact Mapping', 'Jobs-to-be-Done', 'KPIs', 'Kanban', 'LeSS', 'Lean UX', 'Microservices Architecture', 'Mob Programming', 'Monorepo', 'Nexus', 'OKRs', 'Pair Programming', 'Refactoring', 'Retrospectives', 'SAFe', 'SOLID Principles', 'Scrum', 'Serverless Architecture', 'Shape Up', 'Sprint Planning', 'Standup Meetings', 'Story Mapping', 'Technical Debt Management',
        'Test-Driven Development (TDD)', 'Value Stream Mapping', 'Velocity Tracking', 'Waterfall', 'XP (Extreme Programming)'],

    'Big Data': ['Amazon Redshift', 'Apache Airflow', 'Apache Beam', 'Apache Cassandra', 'Apache Druid', 'Apache Flink', 'Apache HBase', 'Apache Hadoop', 'Apache Hive', 'Apache Iceberg', 'Apache Kafka', 'Apache Kylin', 'Apache NiFi', 'Apache Pinot', 'Apache Pulsar', 'Apache Spark', 'Apache Storm', 'Avro', 'Batch Processing', 'Business Intelligence', 'Data Catalog', 'Data Governance', 'Data Ingestion', 'Data Lakes', 'Data Lineage', 'Data Mesh', 'Data Modeling', 'Data Pipelines', 'Data Quality', 'Data Visualization', 'Data Warehousing', 'Databricks', 'Delta Lake', 'ETL / ELT', 'Google BigQuery', 'JSON', 'Looker', 'MapReduce', 'Master Data Management', 'OLAP', 'OLTP', 'ORC', 'Parquet', 'Power BI', 'Presto', 'Protobuf', 'Snowflake', 'Stream Processing', 'Tableau', 'Thrift', 'Trino', 'dbt'],

    'Low-Code/No-Code': ['Adalo', 'Airtable', 'AppGyver', 'AppSheet', 'Appian', 'Bubble', 'Coda', 'Fibery', 'Glide', 'Internal.io', 'Make (Integromat)', 'Mendix', 'Microsoft Power Platform', 'Notion', 'Oracle APEX', 'OutSystems', 'Power Apps', 'Power Automate', 'Power BI', 'Retool', 'Salesforce Platform', 'ServiceNow', 'Softr', 'Tray.io', 'UI Bakery', 'Webflow', 'Workato', 'Zapier', 'n8n'],

    'Soft Skills': ['Accountability', 'Active Listening', 'Adaptability', 'Agility', 'Business Acumen', 'Coaching', 'Collaboration', 'Communication', 'Conflict Resolution', 'Continuous Learning', 'Creativity', 'Critical Thinking', 'Cross-Cultural Communication', 'Customer Service', 'Decision Making', 'Documentation', 'Emotional Intelligence', 'Empathy', 'Feedback Giving & Receiving', 'Leadership', 'Meeting Facilitation', 'Mentorship', 'Negotiation', 'Presentation Skills', 'Problem-Solving', 'Project Management', 'Public Speaking', 'Remote Work', 'Resilience', 'Self-Motivation', 'Stakeholder Management', 'Strategic Thinking', 'Stress Management', 'Teamwork', 'Technical Writing', 'Time Management', 'Work-Life Balance'],

    'Data Science & Analytics': ['Anomaly Detection', 'Business Intelligence', 'Churn Prediction', 'Classification', 'Clustering', 'Cohort Analysis', 'Customer Segmentation', 'Dashboard Design', 'Data Analysis', 'Data Cleaning', 'Data Modeling', 'Data Transformation', 'Data Visualization', 'Database Optimization', 'Descriptive Analytics', 'Diagnostic Analytics', 'Dimensionality Reduction', 'ETL Processes', 'Financial Modeling', 'Forecasting', 'Funnel Analysis', 'Hypothesis Testing', 'Market Basket Analysis', 'Natural Language Processing', 'Predictive Analytics', 'Prescriptive Analytics', 'Regression Analysis', 'Reporting', 'Retention Analysis', 'Sentiment Analysis', 'Statistical Analysis', 'Text Mining', 'Time Series Analysis', 'Web Scraping']
}

module.exports = softwareEngineeringSkills;
